# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a0751ebd2411594dc2936d9d22ebcc995c0f6ed5d31453407dfb7e0e3f3612c9ffedac4f97f8823b70bd31df0d890dbb6877e7c9654be1145f0899a158b1ce6

test:
  secret_key_base: e73948fb970c0ad189b2d96a413204bb7b5ecb19b6eda280ced5a018499d8d4b846ba21d3c4c05f62898db782cc195e1af7ad96c0d8a6ba2955e398c6499a9b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
