# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7748038a043c72f38c93cf22078b434720eb3f55bddf2fcd338982dffa497c0c60a79ca5ebfb7385a371181f49e7f9037c155cd5ba0ac0731734dc0366c714c

test:
  secret_key_base: 9176f609b8b504960f7aa5b4439bba4b2472640efe66a44db8d931020e35b8c63c1653db8440ae5e2c7ad93f900a01b7c801605b0745b7b54d317dce1a353eec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
